apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-depl 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: multisyscorp/web101
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 150m
            memory: 128Mi